config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts
    resources :projects
  end

  resources :contacts, only: [:new, :create]
 
  get 'welcome/index' 
  root 'welcome#index'

   get 'posts/theposts' => 'posts#theposts'
   get 'projects/theprojects' => 'projects#theprojects'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
 attribute :name, :validate => true
 attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
 attribute :message, :validate => true
 attribute :nickname, :captcha => true

 def headers
   {
    :subject => "Contact Form",
    :to => "info@pluginenergy.net",
    :from => %("#{name}" <#{email}>)
   }
 end
end

app/models/post.rb
class Post < ActiveRecord::Base
 belongs_to :user

 extend FriendlyId
 friendly_id :title, use: :slugged

  has_attached_file :plug_thumbnail, styles: { large: "640x480#",medium: "480x360#", thumb: "100x100#" }
  validates_attachment_content_type :plug_thumbnail, content_type: /\Aimage\/.*\Z/



end

app/models/project.rb
class Project < ActiveRecord::Base
 belongs_to :user

 extend FriendlyId
 friendly_id :title, use: :slugged


  has_attached_file :proj_thumbnail, styles: { large: "640x480#",medium: "480x360#", thumb: "100x100#" }
  validates_attachment_content_type :proj_thumbnail, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :posts


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 def new
  @contact = Contact.new
 end

 def create
  @contact = Contact.new(params[:contact])
  @contact.request = request
  if @contact.deliver
   flash.now[:error] = nil
  else
   flash.now[:error] = 'Cannot send message.'
   render :new
  end
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show, :theposts]
 
 before_action :find_user, except: [:index, :show, :theposts]
 before_action :find_post, only: [:show, :edit, :update, :destroy]

 def theposts
  @allposts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 7)
 end

 def index
  @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
 end

 def new
  @post = @user.posts.new
 end

 def create
  @post = @user.posts.new post_params

  if @post.save
   redirect_to user_post_path(@user, @post), notice: "Thank you for submitting a new post!"
  else
   render 'new', notice: "Something went wrong. Please resubmit the post."
  end
 end

 def show
 end

 def edit
 end

 def update
  if @post.update post_params
   redirect_to user_post_path(@user, @post), notice: "You have successfully updated the post."
  else
   render 'edit'
  end
 end

 def destroy
  @post.destroy
  redirect_to user_posts_path
 end

 private
 def post_params
  params.require(:post).permit(:title, :plug_thumbnail, :content, :slug)
 end

 def find_post
  @post = Post.friendly.find(params[:id])
 end

 def find_user
  @user = User.find(params[:user_id])
 end

 def require_permission
  @user = User.find(params[:user_id])
  if current_user != @user
   redirect_to root_path, notice: "Please sign up with the right credentials to view that post."
  end
 end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show, :theprojects]

 before_action :find_user, except: [:index, :show, :theprojects]
 before_action :find_project, only: [:show, :edit, :update, :destroy]

 def theprojects
  @allprojects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 7)
 end 

 def index
  @projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
 end

 def new
  @project = @user.projects.new
 end

 def create
  @project = @user.projects.new project_params
  
  if @project.save
   redirect_to user_project_path(@user, @project), notice: "Your project was successfully saved."
  else
   render 'new'
  end
 end

 def show
 end

 def edit
 end

 def update
  if @project.update project_params
    redirect_to user_project_path(@user,@project), notice: "Your project was successfully updated."
  else
    render 'edit'
  end
 end

 def destroy
  @project.destroy
  redirect_to projects_path
 end

 private
 def find_project
  @project = Project.friendly.find(params[:id])
 end

 def project_params
  params.require(:project).permit(:title, :proj_thumbnail, :description, :link)
 end

 def find_user
  @user = User.find(params[:user_id])
 end

 def require_permission
  @user = User.find(params[:user_id])
  if current_user != @user
   redirect_to root_path, notice: "Please sign up with the right credentials to view that post."
  end
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 def index
  @posts = Post.all.limit(3).order("created_at desc")
  @projects = Project.all.limit(3).order("created_at desc")  
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
 class HTMLwithPygments < Redcarpet::Render::HTML
  def block_code(code, language)
   Pygments.highlight(code, lexer: language)
  end
 end

 def markdown(content)
  renderer = HTMLwithPygments.new(hard_wrap: true, filter_html:true)
  options = {
   autolink: true,
   no_intra_emphasis: true,
   disable_indented_code_blocks: true,
   fenced_code_blocks: true,
   strikethrough: true,
   superscript: true
  }
  Redcarpet::Markdown.new(renderer,options).render(content).html_safe
 end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>
<div class="skinny_wrapper wrapper_padding">
 <h1> Thank you for your message!</h1>
 <p> We will get back you shortly...</p>
</div>

app/views/contacts/new.html.erb
 <h1 id="page_title">Say Hello!</h1>
 <div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %> 
  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %> 
  <br>

  <%= f.label :email %> <br>
  <%= f.email_field :email, required: true %> 

  <br>

  <%= f.label :message %> <br>
  <%= f.email_field :message, as: :text %>
  
  <div class="hidden">
  <%= f.label :nickname %> <br>
  <%= f.text_field :nickname, hint: 'leave this alone' %>
  </div>
  <%= f.submit 'Send Message', class: 'button' %>  
  <%end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plugin Energy - measuring Africa's pulse!</title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <header id="main_navigation" class="clearfix">
   <%= link_to "Plugin Energy", root_path, class: "name" %>
  <nav>
   <%= link_to "Articles", posts_theposts_path %>
   <%= link_to "Projects", projects_theprojects_path %>
   <% if user_signed_in? %>
   <%= link_to "New Post", new_user_post_path(current_user, @post) %>
   <%= link_to "New Project", new_user_project_path(current_user, @project) %>
     <%= link_to "Account", edit_user_registration_path %>
     <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <%= link_to "Contacts", new_contact_path %>
    <% else %>
    <%= link_to "Log In", new_user_session_path %>
    <%= link_to "Contacts", new_contact_path %>
    <% end %> 
  </nav>
 </header>

   <% if notice %>
       <p class="notice"><%= notice %></p>
   <% elsif alert %>
       <p class="alert"><%= alert %></p>
   <% end %>

 <%= yield %>
 <footer id="main_footer">
  <p class="copyright">	&#169; 2016 Plugin Energy - Feel Africa's Pulse.</p>
  <nav>
   <a href="http://facebook.com/getpluginpulse" target="_blank"><i class="fa fa-facebook-square"></i></a>
   <a href="http://twitter.com/getpluginpulse" target="_blank"><i class="fa fa-twitter-square"></i></a>
   <a href="http://linkedin.com/getpluginpulse" target="_blank"><i class="fa fa-linkedin-square"></i></a>
  </nav>
 </footer>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71854585-1', 'auto');
  ga('send', 'pageview');

</script>




</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/

/*Configuration Variables */
var disqus_shortname ='pluginenergy';
var disqus_identifier = '<%= @post.id %> ';
var disqus_title = '<%= @post.title %> ';
var disqus_url = '<%= url_for(user_post_path(4, @post)) %>';

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//pluginenergy.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for ([@user, @post]) do |f| %>
 <% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
  <ul>
   <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
  </ul>
 <%end %>

  <%= f.label :title %> <br>
  <%= f.text_field :title %> 

  <br>
  <br>

  <%= f.label :plug_thumbnail %> <br>
  <%= f.file_field :plug_thumbnail %>

  <br>
  <br>

  <%= f.label :content, "Write your article here." %> <br>
  <%= f.text_area :content %> 

  <br>
  <br>

  <%= f.submit %> 

<% end %>

app/views/posts/edit.html.erb
 <h1 id="page_title"> Edit Post </h1>
 <div class="skinny_wrapper wrapper_padding">
 <%= render 'form' %> 
 </div>

app/views/posts/index.html.erb
<h1 id="page_title">Articles we've written</h1>
 <div id="posts_wrapper" class ="skinny_wrapper">
  <% @posts.each do |post| %> 

    <div class="post">
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
      <h2><a href="#"><%= link_to post.title, user_post_path(current_user, post) %></a></h2>
      <hr>
    </div>

  <% end %>  
 </div>

 <%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title"> New Post</h1>
<div class="skinny_wrapper wrapper_padding">
<%= render 'form' %> 
</div>

app/views/posts/show.html.erb
 <div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
   <p class="date"><%= @post.created_at.strftime('%A, %B %d')%></p>
   <h1><%= @post.title %></h1>
   <hr>
   <div id="episode_content">
    <%= image_tag @post.plug_thumbnail.url(:large), class: "current_episode_thumbnail" %>
    <hr/>
   </div>
  </header>

  <div id="content">
   <%= markdown @post.content %> 
  </div>
  <% if user_signed_in? %>
   <div id="admin_links">
    <%= link_to "Edit Article", edit_user_post_path(current_user,@post) %>
    <%= link_to "Delete Article", user_post_path(current_user,@post), method: :delete, data: {confirm: "Are you sure you want to delete this article?"} %>
   </div>
  <% end %>
  <hr>
  <div id="share_box">
   <p>Share <%= @post.title %></p>
   <!--Twitter-->
   <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @getplugin - &amp;url=<%= url_for(user_post_path(4,@post)) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
   <!--Facebook-->
   <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for(user_post_path(4,@post)) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
   <!--Google Plus-->
   <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for(user_post_path(4,@post)) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
   <!--LinkedIn-->
   <a onclick="javascript:window.open('http://www.linkedin.com/shareArticle?mini=true&amp;url=<%= url_for(user_post_path(4,@post)) %>&amp;title=<%= @post.title %>&amp;summary=<%= truncate(@post.content, :length=>140) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-linkedin"></i></a>
  </div>
  <hr>

  <%= render 'disqus' %> 
 </div> 


<br>
<br>

app/views/posts/theposts.html.erb
<div class="wrapper wrapper_padding clearfix">

<div class="homepage_content post_wrapper skinny_wrapper">
  <h2>Articles we've written</h2>
  <hr>

  <% @allposts.each do |post| %>
   <h3><a href="#"><%= link_to post.title, user_post_path(4, post) %></a></h3>
   <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
  <% end %>
</div>
</div>

<%= will_paginate @allposts %>

app/views/projects/_form.html.erb
<%= form_for ([@user, @project]) do |f| %>
 <% if @project.errors.any? %>
  <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
  <ul>
   <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
  </ul>
 <%end %>

  <%= f.label :title %> <br>
  <%= f.text_field :title %> 

  <br>
  <br>

  <%= f.label :proj_thumbnail %> <br>
  <%= f.file_field :proj_thumbnail %>

  <br>
  <br>

  <%= f.label :description, "Write your project here." %> <br>
  <%= f.text_area :description %> 

  <br>
  <br>

  <%= f.label :link %> <br>
  <%= f.text_field :link %>

  <br>
  <br>

  <%= f.submit %> 

<% end %>

app/views/projects/edit.html.erb
 <h1 id="page_title"> Edit Project </h1>
 <div class="skinny_wrapper wrapper_padding">
 <%= render 'form' %>
 </div>

app/views/projects/index.html.erb
<h1 id="page_title">What we are working on</h1>
 <div id="posts_wrapper" class ="skinny_wrapper">
  <% @projects.each do |project| %>

    <div class="post">
      <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
      <h2><a href="#"><%= link_to project.title, user_project_path(current_user, project) %></a></h2>
      <hr>
    </div>

  <% end %>
 </div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Project</h1>
   <%= render 'form' %> 
</div>

app/views/projects/show.html.erb
 <div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
   <p class="date"><%= @project.created_at.strftime('%A, %B %d')%>
</p>
   <h1><%= @project.title %></h1>
   <hr>
   <div id="episode_content">
    <%= image_tag @project.proj_thumbnail.url(:large), class: "current_episode_thumbnail" %>
    <hr/>
   </div>
  </header>

  <div id="content">
   <%= markdown @project.description %>

   <div class="button_wrapper">
    <a href="<%= @project.link %>" class="project_button" target="_blank"> Visit <%= @project.title %> </a>
   </div>

  </div>
<% if user_signed_in? %>
 <div id="admin_links">
  <%= link_to "Edit Project", edit_user_project_path(current_user, @project) %>
  <%= link_to "Delete Project", user_project_path(current_user, @project), method: :delete, data: {confirm: "Are you sure you want to delete this project?"} %>
 </div>
<% end %>
 
  <hr>

 </div>

app/views/projects/theprojects.html.erb
<div class="wrapper wrapper_padding clearfix">
 <div class="homepage_content post_wrapper skinny_wrapper">
   <h2>What we are Working on</h2>
   <hr>
  <% @allprojects.each do |project| %>
    <h3><a href="#"><%= link_to project.title, user_project_path(4, project) %></a></h3>
    <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
  <% end %>
 </div>
</div>

<%= will_paginate @allprojects %>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
 <div class="col-1 about homepage_content">
  <h2>About</h2>
  <hr>
<h3>The problem</h3>
<p>Reliable energy consumption data in form of profiles and footprint is not available to decision makers in a format they can use to make investment decisions.</p> 
<p>PlugIn energy monitors, measures and provides data to decision makers in a format they can use so they can make the decisions on adoption of renewable energy or understand their energy needs better. <a href="http://www.negawattchallenge.com/">See Here.</a></p>
 </div>

 <div class="col-2 homepage_content">
  <h2>Articles we've written</h2>
  <hr>

  <% @posts.each do |post| %> 
   <h3><a href="#"><%= link_to post.title, user_post_path(4, post) %></a></h3>
   <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
  <% end %>
 </div>

 <div class="col-3 homepage_content">
   <h2>What we are Working on</h2>
   <hr>
  <% @projects.each do |project| %>
    <h3><a href="#"><%= link_to project.title, user_project_path(4, project) %></a></h3>
    <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
  <% end %>
 </div>
</div>